### PR TITLE
Gozure post

### PR DESCRIPTION
**Pull request by makarski**

### CODE REVIEW

**Comment by makarski** [comment]
@maximevaly, please have a look.

**Comment by maximevaly** [comment]
@makarski can you please update the begin of the file so that it matches Jekyll's posts structure?

See https://raw.githubusercontent.com/Onefootball/onefootball.github.io/master/_posts/2015-07-08-Hello.md and http://www.smashingmagazine.com/2014/08/01/build-blog-jekyll-github-pages/#4-publish-your-first-blog-post

**Comment by makarski** [comment]
what category do you prefer?

**Comment by makarski** [comment]
Updated the PR

**Comment by makarski** [comment]
@maximevaly, updated the post as discussed. Need to put an author name still, do you have an idea where?

**Comment by maximevaly** [comment]
@makarski Thanks, I'm not sure yet how to handle the authors, probably something along those lines http://frontedgedigital.com/posts/managing-multiple-authors-with-jekyll/
I'll look into that soon.

**Pull request merged**
